[package]
name = "RustChat"
version = "0.1.0"
authors = ["Geoff Finch <gfinch1@gmail.com>"]

[dependencies]
mio = "0.5"
http-muncher = "0.2.1"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"
byteorder = "0.3.*"
